#+title: Recall - Reacll Emacs process history
#+author: Daniel Pettersson
#+language: en

This package =advice-add=s =make-process= and friends to store metadata like; working directory, stdout, start time, end time, exit code and version control revision for Emacs processes.

It defines commands to view and manage both currently running processes and historical processes, accessible via the minibuffer and/or a specialized =tabulated-list= buffer.

Joining the functionality of bash reverse-i-search with =proced=.

Enable process surveillance with =recall-mode=.

Includes integration with =embark= and =consult=.

* Configuration
#+begin_src emacs-lisp
  (use-package recall
    :vc (:url "https://github.com/svaante/recall")
    :bind
    ;; Note: This binding overrides default binding for `find-file-read-only'
    ;; ("C-x C-r" . recall-list)
    ;; Or if minibuffer completion is your preferable interface
    ;; ("C-x C-r" . recall-rerun)
    :config
    (recall-mode))
#+end_src

* Note
As this package advices core functionality, usage might have unintended consequences.  Disable =recall-mode= at the first signs of process spawning troubles.

Package is inspired by detached.el
